/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.panposo.view;

import com.panposo.controller.ControllerProduto;
import com.panposo.model.Produto;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

/**
 *
 * @author geovani pereira dos santos
 */
public class TelaGerenciarProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerenciarProduto
     */
    // Instanciando de controllerProto
    ControllerProduto controlProd = new ControllerProduto();

    public TelaGerenciarProduto() {
        initComponents();

        controlProd.preencheTabela(tabelaProdutos, campoBuscaProduto.getText());

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        // emeplo de como deixar um componente visivel ou nao
        //labelMensagemCadastro.setVisible(Boolean.FALSE);
        // exemplo de mensagem de notificação
        //JOptionPane.showMessageDialog(new JFrame(), "Produto atualizado sucesso");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMenu = new javax.swing.JPanel();
        botaoTelaInicio = new javax.swing.JPanel();
        textoMenuTelaInicio = new javax.swing.JLabel();
        nomeLogo = new javax.swing.JLabel();
        destaqueLogo = new javax.swing.JPanel();
        botaoMenuGerenciarProduto = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        textoMenuGerenciarProduto1 = new javax.swing.JLabel();
        tituloTela = new javax.swing.JPanel();
        textoTituloPagina = new javax.swing.JLabel();
        painelAdicionarProduto = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelNomeProduto = new javax.swing.JLabel();
        textoNomeProduto = new javax.swing.JTextField();
        labelPreco = new javax.swing.JLabel();
        labelUnidade = new javax.swing.JLabel();
        selectBoxUnidadeProduto = new javax.swing.JComboBox<>();
        labeldescricaoProduto = new javax.swing.JLabel();
        textoDescricaoProduto = new javax.swing.JTextField();
        botaoAdicionarProduto = new javax.swing.JButton();
        labelCodigoProduto = new javax.swing.JLabel();
        textoCodigoProduto = new javax.swing.JTextField();
        labelNomeMarca = new javax.swing.JLabel();
        textoMarca = new javax.swing.JTextField();
        labelQuantidade = new javax.swing.JLabel();
        textFormatPrecoProduto = new javax.swing.JFormattedTextField();
        checkBoxHabilitarProduto = new javax.swing.JCheckBox();
        botaoAtualizarProduto = new javax.swing.JButton();
        textUnidade2 = new javax.swing.JFormattedTextField();
        textoQuantidade = new javax.swing.JFormattedTextField();
        painelAtualizarProduto = new javax.swing.JPanel();
        campoBuscaProduto = new javax.swing.JTextField();
        botaoBuscaProduto = new javax.swing.JButton();
        scrollViewTabelaProdutos = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        selectBoxFiltroBuscaProduto = new javax.swing.JComboBox<>();
        labelBusca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 610));

        painelMenu.setBackground(new java.awt.Color(23, 35, 51));

        botaoTelaInicio.setBackground(new java.awt.Color(23, 35, 51));
        botaoTelaInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoTelaInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoTelaInicioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoTelaInicioMousePressed(evt);
            }
        });

        textoMenuTelaInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoMenuTelaInicio.setForeground(new java.awt.Color(204, 204, 255));
        textoMenuTelaInicio.setText("Tela Inicial");

        javax.swing.GroupLayout botaoTelaInicioLayout = new javax.swing.GroupLayout(botaoTelaInicio);
        botaoTelaInicio.setLayout(botaoTelaInicioLayout);
        botaoTelaInicioLayout.setHorizontalGroup(
            botaoTelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoTelaInicioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textoMenuTelaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        botaoTelaInicioLayout.setVerticalGroup(
            botaoTelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoTelaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoMenuTelaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        nomeLogo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nomeLogo.setForeground(new java.awt.Color(204, 204, 255));
        nomeLogo.setText("GambiBox");

        destaqueLogo.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout destaqueLogoLayout = new javax.swing.GroupLayout(destaqueLogo);
        destaqueLogo.setLayout(destaqueLogoLayout);
        destaqueLogoLayout.setHorizontalGroup(
            destaqueLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        destaqueLogoLayout.setVerticalGroup(
            destaqueLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        botaoMenuGerenciarProduto.setBackground(new java.awt.Color(41, 57, 80));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(4, 60));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        textoMenuGerenciarProduto1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoMenuGerenciarProduto1.setForeground(new java.awt.Color(204, 204, 255));
        textoMenuGerenciarProduto1.setText("Gerenciar Produto");

        javax.swing.GroupLayout botaoMenuGerenciarProdutoLayout = new javax.swing.GroupLayout(botaoMenuGerenciarProduto);
        botaoMenuGerenciarProduto.setLayout(botaoMenuGerenciarProdutoLayout);
        botaoMenuGerenciarProdutoLayout.setHorizontalGroup(
            botaoMenuGerenciarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoMenuGerenciarProdutoLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoMenuGerenciarProduto1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        botaoMenuGerenciarProdutoLayout.setVerticalGroup(
            botaoMenuGerenciarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoMenuGerenciarProdutoLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoMenuGerenciarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoMenuGerenciarProduto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout painelMenuLayout = new javax.swing.GroupLayout(painelMenu);
        painelMenu.setLayout(painelMenuLayout);
        painelMenuLayout.setHorizontalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoTelaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destaqueLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(botaoMenuGerenciarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelMenuLayout.setVerticalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(nomeLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destaqueLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoTelaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoMenuGerenciarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tituloTela.setBackground(new java.awt.Color(71, 120, 197));

        textoTituloPagina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoTituloPagina.setForeground(new java.awt.Color(204, 204, 255));
        textoTituloPagina.setText("Gerenciar produto");

        javax.swing.GroupLayout tituloTelaLayout = new javax.swing.GroupLayout(tituloTela);
        tituloTela.setLayout(tituloTelaLayout);
        tituloTelaLayout.setHorizontalGroup(
            tituloTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoTituloPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tituloTelaLayout.setVerticalGroup(
            tituloTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoTituloPagina, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelAdicionarProduto.setBackground(new java.awt.Color(255, 255, 255));
        painelAdicionarProduto.setMinimumSize(new java.awt.Dimension(800, 600));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(102, 102, 102));
        labelTitulo.setText("Adicionar produto");

        labelNomeProduto.setText("Nome");

        labelPreco.setText("Preço");

        labelUnidade.setText("Unidade:");

        selectBoxUnidadeProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "grama (g)", "metro (m)", "centimetro (cm)", "Litro (L)", "ml", "volume", "duzia", "unidade", " " }));
        selectBoxUnidadeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBoxUnidadeProdutoActionPerformed(evt);
            }
        });

        labeldescricaoProduto.setText("Descrição");

        botaoAdicionarProduto.setText("Adicionar produto");
        botaoAdicionarProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarProdutoActionPerformed(evt);
            }
        });

        labelCodigoProduto.setText("Código Produto");

        textoCodigoProduto.setEnabled(false);
        textoCodigoProduto.setFocusable(false);

        labelNomeMarca.setText("Nome da marca");

        labelQuantidade.setText("Quantidade de produto");

        textFormatPrecoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFormatPrecoProdutoActionPerformed(evt);
            }
        });

        checkBoxHabilitarProduto.setSelected(true);
        checkBoxHabilitarProduto.setText("Habilitado");
        checkBoxHabilitarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxHabilitarProdutoActionPerformed(evt);
            }
        });

        botaoAtualizarProduto.setText("Atualizar produto");

        textoQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        textoQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoQuantidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelAdicionarProdutoLayout = new javax.swing.GroupLayout(painelAdicionarProduto);
        painelAdicionarProduto.setLayout(painelAdicionarProdutoLayout);
        painelAdicionarProdutoLayout.setHorizontalGroup(
            painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                        .addComponent(labelNomeMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(checkBoxHabilitarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoAtualizarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoAdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                        .addGroup(painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo)
                            .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                                .addComponent(labelCodigoProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelUnidade)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textUnidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectBoxUnidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFormatPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 365, Short.MAX_VALUE))
                    .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                        .addComponent(labelNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labeldescricaoProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoDescricaoProduto)))
                .addGap(34, 34, 34))
        );
        painelAdicionarProdutoLayout.setVerticalGroup(
            painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeProduto)
                    .addComponent(textoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeldescricaoProduto)
                    .addComponent(textoDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCodigoProduto)
                    .addComponent(labelPreco)
                    .addComponent(labelQuantidade)
                    .addComponent(labelUnidade)
                    .addComponent(selectBoxUnidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFormatPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textUnidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeMarca)
                    .addComponent(textoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxHabilitarProduto)
                    .addComponent(botaoAdicionarProduto)
                    .addComponent(botaoAtualizarProduto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelAtualizarProduto.setBackground(new java.awt.Color(255, 255, 255));

        botaoBuscaProduto.setText("Buscar Produto");
        botaoBuscaProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoBuscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscaProdutoActionPerformed(evt);
            }
        });

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Descricão", "Preço", "Unidade", "qtd estoque", "Nome Marca"
            }
        ));
        scrollViewTabelaProdutos.setViewportView(tabelaProdutos);

        selectBoxFiltroBuscaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos os produtos", "Código do produto", "Nome do produto", "Descrição do produto" }));

        labelBusca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelBusca.setText("Buscar");

        javax.swing.GroupLayout painelAtualizarProdutoLayout = new javax.swing.GroupLayout(painelAtualizarProduto);
        painelAtualizarProduto.setLayout(painelAtualizarProdutoLayout);
        painelAtualizarProdutoLayout.setHorizontalGroup(
            painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollViewTabelaProdutos)
                    .addGroup(painelAtualizarProdutoLayout.createSequentialGroup()
                        .addComponent(labelBusca)
                        .addGap(18, 18, 18)
                        .addComponent(campoBuscaProduto)
                        .addGap(18, 18, 18)
                        .addComponent(selectBoxFiltroBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        painelAtualizarProdutoLayout.setVerticalGroup(
            painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAtualizarProdutoLayout.createSequentialGroup()
                        .addGroup(painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoBuscaProduto)
                            .addComponent(selectBoxFiltroBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoBuscaProduto))
                        .addGap(13, 13, 13))
                    .addGroup(painelAtualizarProdutoLayout.createSequentialGroup()
                        .addComponent(labelBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(scrollViewTabelaProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelAdicionarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelAtualizarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelAdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelAtualizarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscaProdutoActionPerformed

        //Clique do Botao buscar
        //controlProd.buscarProdutos(tabelaProdutos, textoNomeProduto.getText());
        controlProd.preencheTabela(tabelaProdutos, campoBuscaProduto.getText());
    }//GEN-LAST:event_botaoBuscaProdutoActionPerformed

    private void botaoAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarProdutoActionPerformed

        if (textoNomeProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome do produto não informado!");
        } else if (textFormatPrecoProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preço do produto não informado!");
        } else {
            // salvando os dados no banco
            boolean cadasProd = controlProd.cadastraProduto(textoNomeProduto.getText(),
                    textoDescricaoProduto.getText(),
                    Integer.parseInt(textUnidade2.getText()),
                    Integer.parseInt(textUnidade2.getText()),
                    selectBoxUnidadeProduto.getSelectedItem().toString(),
                    Double.parseDouble(textFormatPrecoProduto.getText()),
                    textoMarca.getText());

            // Mensagem apresentada ao usuário sobre a persistência dos dados
            if (!cadasProd) {
                JOptionPane.showMessageDialog(null, "Erro ao salvar os dados");
            } else {
                // se persistência o correu corretamente
                JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!");

                controlProd.limpaCampos(textoNomeProduto, textoDescricaoProduto, textoQuantidade, textUnidade2, textFormatPrecoProduto, textoMarca);
            }
        }

    }//GEN-LAST:event_botaoAdicionarProdutoActionPerformed


    private void selectBoxUnidadeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBoxUnidadeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectBoxUnidadeProdutoActionPerformed


    private void checkBoxHabilitarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxHabilitarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxHabilitarProdutoActionPerformed


    private void botaoTelaInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaInicioMousePressed
        new TelaInicial().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoTelaInicioMousePressed

    private void botaoTelaInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaInicioMouseEntered
        setColor(botaoTelaInicio);
    }//GEN-LAST:event_botaoTelaInicioMouseEntered

    private void botaoTelaInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaInicioMouseExited
        resetColor(botaoTelaInicio);
    }//GEN-LAST:event_botaoTelaInicioMouseExited

    private void textFormatPrecoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFormatPrecoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFormatPrecoProdutoActionPerformed

    private void textoQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoQuantidadeActionPerformed
       textoQuantidade = new javax.swing.JFormattedTextField();
       textoQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())) );
    }//GEN-LAST:event_textoQuantidadeActionPerformed

    private void setColor(JPanel panel) {
        panel.setBackground(new Color(41, 57, 80));
    }

    private void resetColor(JPanel panel) {
        panel.setBackground(new Color(23, 35, 51));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionarProduto;
    private javax.swing.JButton botaoAtualizarProduto;
    private javax.swing.JButton botaoBuscaProduto;
    private javax.swing.JPanel botaoMenuGerenciarProduto;
    private javax.swing.JPanel botaoTelaInicio;
    private javax.swing.JTextField campoBuscaProduto;
    private javax.swing.JCheckBox checkBoxHabilitarProduto;
    private javax.swing.JPanel destaqueLogo;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelBusca;
    private javax.swing.JLabel labelCodigoProduto;
    private javax.swing.JLabel labelNomeMarca;
    private javax.swing.JLabel labelNomeProduto;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUnidade;
    private javax.swing.JLabel labeldescricaoProduto;
    private javax.swing.JLabel nomeLogo;
    private javax.swing.JPanel painelAdicionarProduto;
    private javax.swing.JPanel painelAtualizarProduto;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JScrollPane scrollViewTabelaProdutos;
    private javax.swing.JComboBox<String> selectBoxFiltroBuscaProduto;
    private javax.swing.JComboBox<String> selectBoxUnidadeProduto;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JFormattedTextField textFormatPrecoProduto;
    private javax.swing.JFormattedTextField textUnidade2;
    private javax.swing.JTextField textoCodigoProduto;
    private javax.swing.JTextField textoDescricaoProduto;
    private javax.swing.JTextField textoMarca;
    private javax.swing.JLabel textoMenuGerenciarProduto1;
    private javax.swing.JLabel textoMenuTelaInicio;
    private javax.swing.JTextField textoNomeProduto;
    private javax.swing.JFormattedTextField textoQuantidade;
    private javax.swing.JLabel textoTituloPagina;
    private javax.swing.JPanel tituloTela;
    // End of variables declaration//GEN-END:variables
}
