/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.GambiBox.view;

import com.GambiBox.controller.ControllerProduto;
import com.GambiBox.controller.ControllerVenda;
import com.GambiBox.model.Produto;
import com.GambiBox.model.TextPrompt;
import com.GambiBox.model.ItemProdutoTableModel;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Giovane Richard
 */
public class TelaGerenciarVenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerenciarVenda
     */
    // Instancia de controller venda e produto
    ControllerVenda controlVenda = new ControllerVenda();
    ControllerProduto controlProd = new ControllerProduto();

    // Instanciando ItemProdutoTableModel
    ItemProdutoTableModel tableModelVenda = new ItemProdutoTableModel();

    public TelaGerenciarVenda() {
        initComponents();

        // informa qual a tabela para TableModel
        tabelaVenda.setModel(tableModelVenda);

        // altera o layout da tabela vendas
        visualTabela();
        
        // carrega os campos com os placeholdes
        placeHolderCampos();
        
        // inicializa a quantidade de itens com default 1 ítem
        textoQuantidadeProdutos.setText("1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMenu = new javax.swing.JPanel();
        nomeLogo = new javax.swing.JLabel();
        botaoTelaInicio = new javax.swing.JPanel();
        textoMenuTelaInicio = new javax.swing.JLabel();
        destaqueLogo = new javax.swing.JPanel();
        botaoMenuGerenciarProduto = new javax.swing.JPanel();
        textoMenuGerenciarProduto1 = new javax.swing.JLabel();
        botaoTelaGerenciarEstoque = new javax.swing.JPanel();
        textoMenuTelaGerenciarEstoque = new javax.swing.JLabel();
        botaoTelaGerenciarVenda = new javax.swing.JPanel();
        textoMenuTelaGerenciarVenda = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        tituloTela = new javax.swing.JPanel();
        textoTituloPagina = new javax.swing.JLabel();
        painelAdicionarProduto = new javax.swing.JPanel();
        labelFormaPagamento = new javax.swing.JLabel();
        selectBoxFormaPagamento = new javax.swing.JComboBox<>();
        botaoRemoverItemListaProdutos = new javax.swing.JButton();
        botaoCancelarVenda = new javax.swing.JButton();
        painelAtualizarProduto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVenda = new javax.swing.JTable();
        labelQuantidadeProdutos = new javax.swing.JLabel();
        textoQuantidadeProdutos = new javax.swing.JTextField();
        labelCodigoProduto = new javax.swing.JLabel();
        textoCodigoProduto = new javax.swing.JTextField();
        botaoAdicionarProduto = new javax.swing.JButton();
        botaoFinalizarVenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDinheiro = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        labelSubTotal = new javax.swing.JLabel();
        textoSubTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        painelMenu.setBackground(new java.awt.Color(23, 35, 51));

        nomeLogo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nomeLogo.setForeground(new java.awt.Color(204, 204, 255));
        nomeLogo.setText("GambiBox");

        botaoTelaInicio.setBackground(new java.awt.Color(23, 35, 51));
        botaoTelaInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoTelaInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoTelaInicioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoTelaInicioMousePressed(evt);
            }
        });

        textoMenuTelaInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoMenuTelaInicio.setForeground(new java.awt.Color(204, 204, 255));
        textoMenuTelaInicio.setText("Tela Inicial");
        textoMenuTelaInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout botaoTelaInicioLayout = new javax.swing.GroupLayout(botaoTelaInicio);
        botaoTelaInicio.setLayout(botaoTelaInicioLayout);
        botaoTelaInicioLayout.setHorizontalGroup(
            botaoTelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoTelaInicioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textoMenuTelaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        botaoTelaInicioLayout.setVerticalGroup(
            botaoTelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoTelaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoMenuTelaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        destaqueLogo.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout destaqueLogoLayout = new javax.swing.GroupLayout(destaqueLogo);
        destaqueLogo.setLayout(destaqueLogoLayout);
        destaqueLogoLayout.setHorizontalGroup(
            destaqueLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        destaqueLogoLayout.setVerticalGroup(
            destaqueLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        botaoMenuGerenciarProduto.setBackground(new java.awt.Color(23, 35, 51));
        botaoMenuGerenciarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMenuGerenciarProdutoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoMenuGerenciarProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoMenuGerenciarProdutoMouseExited(evt);
            }
        });

        textoMenuGerenciarProduto1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoMenuGerenciarProduto1.setForeground(new java.awt.Color(204, 204, 255));
        textoMenuGerenciarProduto1.setText("Gerenciar Produto");
        textoMenuGerenciarProduto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout botaoMenuGerenciarProdutoLayout = new javax.swing.GroupLayout(botaoMenuGerenciarProduto);
        botaoMenuGerenciarProduto.setLayout(botaoMenuGerenciarProdutoLayout);
        botaoMenuGerenciarProdutoLayout.setHorizontalGroup(
            botaoMenuGerenciarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoMenuGerenciarProdutoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textoMenuGerenciarProduto1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        botaoMenuGerenciarProdutoLayout.setVerticalGroup(
            botaoMenuGerenciarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoMenuGerenciarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoMenuGerenciarProduto1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        botaoTelaGerenciarEstoque.setBackground(new java.awt.Color(23, 35, 51));
        botaoTelaGerenciarEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoTelaGerenciarEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoTelaGerenciarEstoqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoTelaGerenciarEstoqueMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoTelaGerenciarEstoqueMousePressed(evt);
            }
        });

        textoMenuTelaGerenciarEstoque.setBackground(new java.awt.Color(41, 57, 80));
        textoMenuTelaGerenciarEstoque.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoMenuTelaGerenciarEstoque.setForeground(new java.awt.Color(204, 204, 255));
        textoMenuTelaGerenciarEstoque.setText("Gerenciar Estoque");
        textoMenuTelaGerenciarEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textoMenuTelaGerenciarEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoMenuTelaGerenciarEstoqueMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botaoTelaGerenciarEstoqueLayout = new javax.swing.GroupLayout(botaoTelaGerenciarEstoque);
        botaoTelaGerenciarEstoque.setLayout(botaoTelaGerenciarEstoqueLayout);
        botaoTelaGerenciarEstoqueLayout.setHorizontalGroup(
            botaoTelaGerenciarEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoTelaGerenciarEstoqueLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(textoMenuTelaGerenciarEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        botaoTelaGerenciarEstoqueLayout.setVerticalGroup(
            botaoTelaGerenciarEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoTelaGerenciarEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoMenuTelaGerenciarEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        botaoTelaGerenciarVenda.setBackground(new java.awt.Color(41, 57, 80));
        botaoTelaGerenciarVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoTelaGerenciarVendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoTelaGerenciarVendaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoTelaGerenciarVendaMousePressed(evt);
            }
        });

        textoMenuTelaGerenciarVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoMenuTelaGerenciarVenda.setForeground(new java.awt.Color(204, 204, 255));
        textoMenuTelaGerenciarVenda.setText("Gerenciar Venda");
        textoMenuTelaGerenciarVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textoMenuTelaGerenciarVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoMenuTelaGerenciarVendaMouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(3, 60));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout botaoTelaGerenciarVendaLayout = new javax.swing.GroupLayout(botaoTelaGerenciarVenda);
        botaoTelaGerenciarVenda.setLayout(botaoTelaGerenciarVendaLayout);
        botaoTelaGerenciarVendaLayout.setHorizontalGroup(
            botaoTelaGerenciarVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoTelaGerenciarVendaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textoMenuTelaGerenciarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(botaoTelaGerenciarVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botaoTelaGerenciarVendaLayout.createSequentialGroup()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 176, Short.MAX_VALUE)))
        );
        botaoTelaGerenciarVendaLayout.setVerticalGroup(
            botaoTelaGerenciarVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoTelaGerenciarVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoMenuTelaGerenciarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(botaoTelaGerenciarVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelMenuLayout = new javax.swing.GroupLayout(painelMenu);
        painelMenu.setLayout(painelMenuLayout);
        painelMenuLayout.setHorizontalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoTelaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destaqueLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(botaoMenuGerenciarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoTelaGerenciarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoTelaGerenciarEstoque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelMenuLayout.setVerticalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(nomeLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destaqueLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoTelaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoMenuGerenciarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoTelaGerenciarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoTelaGerenciarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );

        tituloTela.setBackground(new java.awt.Color(71, 120, 197));

        textoTituloPagina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoTituloPagina.setForeground(new java.awt.Color(204, 204, 255));
        textoTituloPagina.setText("Gerenciar venda");

        javax.swing.GroupLayout tituloTelaLayout = new javax.swing.GroupLayout(tituloTela);
        tituloTela.setLayout(tituloTelaLayout);
        tituloTelaLayout.setHorizontalGroup(
            tituloTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoTituloPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tituloTelaLayout.setVerticalGroup(
            tituloTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoTituloPagina, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelAdicionarProduto.setBackground(new java.awt.Color(255, 255, 255));
        painelAdicionarProduto.setMinimumSize(new java.awt.Dimension(800, 600));

        labelFormaPagamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelFormaPagamento.setText("Forma de pagamento");

        selectBoxFormaPagamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectBoxFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão" }));
        selectBoxFormaPagamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectBoxFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBoxFormaPagamentoActionPerformed(evt);
            }
        });

        botaoRemoverItemListaProdutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoRemoverItemListaProdutos.setText("Remover item");
        botaoRemoverItemListaProdutos.setEnabled(false);
        botaoRemoverItemListaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverItemListaProdutosActionPerformed(evt);
            }
        });

        botaoCancelarVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoCancelarVenda.setText("Cancelar venda");
        botaoCancelarVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelAdicionarProdutoLayout = new javax.swing.GroupLayout(painelAdicionarProduto);
        painelAdicionarProduto.setLayout(painelAdicionarProdutoLayout);
        painelAdicionarProdutoLayout.setHorizontalGroup(
            painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFormaPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectBoxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199)
                .addComponent(botaoRemoverItemListaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(botaoCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        painelAdicionarProdutoLayout.setVerticalGroup(
            painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectBoxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRemoverItemListaProdutos)
                    .addComponent(botaoCancelarVenda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelAtualizarProduto.setBackground(new java.awt.Color(255, 255, 255));

        tabelaVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaVenda);

        labelQuantidadeProdutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelQuantidadeProdutos.setText("Quantidade");

        labelCodigoProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCodigoProduto.setText("Código");

        botaoAdicionarProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoAdicionarProduto.setText("Adicionar produto");
        botaoAdicionarProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarProdutoActionPerformed(evt);
            }
        });

        botaoFinalizarVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoFinalizarVenda.setText("Finalizar venda");
        botaoFinalizarVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinalizarVendaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Valor pago R$");

        jTextFieldDinheiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDinheiroActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(41, 57, 80));

        labelSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelSubTotal.setForeground(new java.awt.Color(204, 204, 255));
        labelSubTotal.setText("Subtotal  R$");

        textoSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoSubTotal.setForeground(new java.awt.Color(204, 204, 255));
        textoSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoSubTotal.setText("0,0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSubTotal)
                .addGap(18, 18, 18)
                .addComponent(textoSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(textoSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Lista de produtos");

        javax.swing.GroupLayout painelAtualizarProdutoLayout = new javax.swing.GroupLayout(painelAtualizarProduto);
        painelAtualizarProduto.setLayout(painelAtualizarProdutoLayout);
        painelAtualizarProdutoLayout.setHorizontalGroup(
            painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelAtualizarProdutoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(botaoFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAtualizarProdutoLayout.createSequentialGroup()
                        .addGroup(painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelQuantidadeProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(labelCodigoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoQuantidadeProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(textoCodigoProduto)
                            .addComponent(botaoAdicionarProduto, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(37, 37, 37))
        );
        painelAtualizarProdutoLayout.setVerticalGroup(
            painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantidadeProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoQuantidadeProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAtualizarProdutoLayout.createSequentialGroup()
                        .addGroup(painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(botaoAdicionarProduto)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoFinalizarVenda))
                        .addGap(85, 85, 85))
                    .addGroup(painelAtualizarProdutoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelAdicionarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelAtualizarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelAdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelAtualizarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoTelaInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaInicioMouseEntered
        setColor(botaoTelaInicio);
    }//GEN-LAST:event_botaoTelaInicioMouseEntered

    private void botaoTelaInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaInicioMouseExited
        resetColor(botaoTelaInicio);
    }//GEN-LAST:event_botaoTelaInicioMouseExited

    private void botaoTelaInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaInicioMousePressed
        controlProd.newTelaInicial();
        dispose();
    }//GEN-LAST:event_botaoTelaInicioMousePressed

    private void botaoMenuGerenciarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMenuGerenciarProdutoMouseClicked
        // TODO add your handling code here:
        controlProd.newTelaProduto();
        dispose();
    }//GEN-LAST:event_botaoMenuGerenciarProdutoMouseClicked

    private void botaoMenuGerenciarProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMenuGerenciarProdutoMouseEntered
        setColor(botaoMenuGerenciarProduto);
    }//GEN-LAST:event_botaoMenuGerenciarProdutoMouseEntered

    private void botaoMenuGerenciarProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMenuGerenciarProdutoMouseExited
        resetColor(botaoMenuGerenciarProduto);
    }//GEN-LAST:event_botaoMenuGerenciarProdutoMouseExited

    private void botaoTelaGerenciarEstoqueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaGerenciarEstoqueMousePressed
        // navegação
    }//GEN-LAST:event_botaoTelaGerenciarEstoqueMousePressed

    private void botaoTelaGerenciarVendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaGerenciarVendaMouseEntered
        setColor(botaoTelaGerenciarVenda);
    }//GEN-LAST:event_botaoTelaGerenciarVendaMouseEntered

    private void botaoTelaGerenciarVendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaGerenciarVendaMouseExited
        resetColor(botaoTelaGerenciarVenda);
    }//GEN-LAST:event_botaoTelaGerenciarVendaMouseExited

    private void botaoTelaGerenciarVendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaGerenciarVendaMousePressed
        // navegação
    }//GEN-LAST:event_botaoTelaGerenciarVendaMousePressed

    private void botaoTelaGerenciarEstoqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaGerenciarEstoqueMouseEntered
        setColor(botaoTelaGerenciarEstoque);
    }//GEN-LAST:event_botaoTelaGerenciarEstoqueMouseEntered

    private void botaoTelaGerenciarEstoqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaGerenciarEstoqueMouseExited
        resetColor(botaoTelaGerenciarEstoque);
    }//GEN-LAST:event_botaoTelaGerenciarEstoqueMouseExited

    private void selectBoxFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBoxFormaPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectBoxFormaPagamentoActionPerformed

    private void botaoRemoverItemListaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverItemListaProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRemoverItemListaProdutosActionPerformed

    private void botaoFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarVendaActionPerformed
        // TODO add your handling code here:
        if(jTextFieldDinheiro.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Valor pago não informado!");
        }
        
        double troco = Double.parseDouble(jTextFieldDinheiro.getText());
        
    }//GEN-LAST:event_botaoFinalizarVendaActionPerformed

    private void jTextFieldDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDinheiroActionPerformed

    private void botaoCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarVendaActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/com/GambiBox/view/imagens/iconAlerta.png");
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente CANCELAR a venda!", "Vedas", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        
        if(opcao == 0){
            controlProd.newTelaInicial();
        }
        
    }//GEN-LAST:event_botaoCancelarVendaActionPerformed

    private void botaoAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarProdutoActionPerformed
        // TODO add your handling code here:

        if(textoQuantidadeProdutos.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Quantidade de produto não informado!");
        }
        
        if(textoCodigoProduto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Código do produto não informado!");
        }
        
        int cod = Integer.parseInt(textoCodigoProduto.getText());
        int quantidade = Integer.parseInt(textoQuantidadeProdutos.getText());
        controlVenda.AdicionarProduto(tableModelVenda, cod, quantidade);
        
        // formatação de apresentação na tabela
        String sf = tableModelVenda.getTotal().toString();
                sf = sf.replace(".", ",");
        textoSubTotal.setText(sf);
        
        // limpa o campo do código
        textoCodigoProduto.setText("");
    }//GEN-LAST:event_botaoAdicionarProdutoActionPerformed

    private void textoMenuTelaGerenciarEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoMenuTelaGerenciarEstoqueMouseClicked
        // TODO add your handling code here:
        controlProd.newTelaEstoque();
        dispose();
    }//GEN-LAST:event_textoMenuTelaGerenciarEstoqueMouseClicked

    private void textoMenuTelaGerenciarVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoMenuTelaGerenciarVendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textoMenuTelaGerenciarVendaMouseClicked

    private void setColor(JPanel panel) {
        panel.setBackground(new Color(41, 57, 80));
    }

    private void resetColor(JPanel panel) {
        panel.setBackground(new Color(23, 35, 51));
    }

     public boolean placeHolderCampos() {

        try {
            TextPrompt pldQtdProd = new TextPrompt("Quantidade de produtos", textoQuantidadeProdutos);
            TextPrompt pldCod = new TextPrompt("Código do Produto", textoCodigoProduto);
            TextPrompt pldPagamento = new TextPrompt("Valor pago", jTextFieldDinheiro);

        } catch (Exception e) {
            return false;
        }

        return true;
    }
    
    // Método que altera a largura da colunas da tabela
    public void visualTabela() {
        tabelaVenda.getColumnModel().getColumn(0).setPreferredWidth(40);
        tabelaVenda.getColumnModel().getColumn(1).setPreferredWidth(300);
        tabelaVenda.getColumnModel().getColumn(2).setPreferredWidth(40);
        tabelaVenda.getColumnModel().getColumn(3).setPreferredWidth(40);
        tabelaVenda.getColumnModel().getColumn(4).setPreferredWidth(40);
        tabelaVenda.getColumnModel().getColumn(5).setPreferredWidth(40);
        tabelaVenda.getColumnModel().getColumn(6).setPreferredWidth(70);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciarVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionarProduto;
    private javax.swing.JButton botaoCancelarVenda;
    private javax.swing.JButton botaoFinalizarVenda;
    private javax.swing.JPanel botaoMenuGerenciarProduto;
    private javax.swing.JButton botaoRemoverItemListaProdutos;
    private javax.swing.JPanel botaoTelaGerenciarEstoque;
    private javax.swing.JPanel botaoTelaGerenciarVenda;
    private javax.swing.JPanel botaoTelaInicio;
    private javax.swing.JPanel destaqueLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldDinheiro;
    private javax.swing.JLabel labelCodigoProduto;
    private javax.swing.JLabel labelFormaPagamento;
    private javax.swing.JLabel labelQuantidadeProdutos;
    private javax.swing.JLabel labelSubTotal;
    private javax.swing.JLabel nomeLogo;
    private javax.swing.JPanel painelAdicionarProduto;
    private javax.swing.JPanel painelAtualizarProduto;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JComboBox<String> selectBoxFormaPagamento;
    private javax.swing.JTable tabelaVenda;
    private javax.swing.JTextField textoCodigoProduto;
    private javax.swing.JLabel textoMenuGerenciarProduto1;
    private javax.swing.JLabel textoMenuTelaGerenciarEstoque;
    private javax.swing.JLabel textoMenuTelaGerenciarVenda;
    private javax.swing.JLabel textoMenuTelaInicio;
    private javax.swing.JTextField textoQuantidadeProdutos;
    private javax.swing.JLabel textoSubTotal;
    private javax.swing.JLabel textoTituloPagina;
    private javax.swing.JPanel tituloTela;
    // End of variables declaration//GEN-END:variables
}
