/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.GambiBox.view;

import com.GambiBox.controller.ControllerProduto;
import com.GambiBox.model.ProdutoTableModel;
import com.GambiBox.model.TextPrompt;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author geova
 */
public class TelaGerenciarEstoque extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerenciarEstoque
     */
    // Instanciando de controllerProduto e controllerEstoque
    ControllerProduto controlProd = new ControllerProduto();

    // Instanciando ProdutoTableModel
    ProdutoTableModel tableModelEstoque = new ProdutoTableModel();

    public TelaGerenciarEstoque() {
        initComponents();

        // informa qual a tabela para TableModel
        tabelaEstoque.setModel(tableModelEstoque);

        // inicializa a tabela com os dados do banco
        controlProd.buscaProduto(tableModelEstoque, null, "", null);

        // inicializa os placeHolders
        placeHolderCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMenu = new javax.swing.JPanel();
        nomeLogo = new javax.swing.JLabel();
        botaoTelaInicio = new javax.swing.JPanel();
        textoMenuTelaInicio = new javax.swing.JLabel();
        destaqueLogo = new javax.swing.JPanel();
        botaoMenuGerenciarProduto = new javax.swing.JPanel();
        textoMenuGerenciarProduto1 = new javax.swing.JLabel();
        botaoTelaGerenciarEstoque = new javax.swing.JPanel();
        textoMenuTelaGerenciarEstoque = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        botaoTelaGerenciarVenda = new javax.swing.JPanel();
        textoMenuTelaGerenciarVenda = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tituloTela = new javax.swing.JPanel();
        textoTituloPagina = new javax.swing.JLabel();
        painelAdicionarProduto = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelNomeProduto = new javax.swing.JLabel();
        textoNomeProduto = new javax.swing.JTextField();
        labelPreco = new javax.swing.JLabel();
        labelUnidade = new javax.swing.JLabel();
        selectBoxUnidadeProduto = new javax.swing.JComboBox<>();
        labeldescricaoProduto = new javax.swing.JLabel();
        textoDescricaoProduto = new javax.swing.JTextField();
        labelCodigoProduto = new javax.swing.JLabel();
        textoCodigoProduto = new javax.swing.JTextField();
        labelNomeMarca = new javax.swing.JLabel();
        textoMarca = new javax.swing.JTextField();
        labelQuantidade = new javax.swing.JLabel();
        textFormatPrecoProduto = new javax.swing.JFormattedTextField();
        try{ javax.swing.text.MaskFormatter real = new javax.swing.text.MaskFormatter("R$ ##.##"); textFormatPrecoProduto = new javax.swing.JFormattedTextField(real); } catch (Exception e){}
        textUnidade2 = new javax.swing.JFormattedTextField();
        textoQuantidade = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        atualizaQtd = new javax.swing.JFormattedTextField();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        checkBoxHabilitarProduto = new javax.swing.JCheckBox();
        painelAtualizarProduto = new javax.swing.JPanel();
        campoBuscaProduto = new javax.swing.JTextField();
        botaoBuscaProduto = new javax.swing.JButton();
        scrollViewTabelaEstoque = new javax.swing.JScrollPane();
        tabelaEstoque = new javax.swing.JTable();
        selectBoxFiltroBuscaProduto = new javax.swing.JComboBox<>();
        labelBusca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        painelMenu.setBackground(new java.awt.Color(23, 35, 51));

        nomeLogo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nomeLogo.setForeground(new java.awt.Color(204, 204, 255));
        nomeLogo.setText("GambiBox");

        botaoTelaInicio.setBackground(new java.awt.Color(23, 35, 51));
        botaoTelaInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoTelaInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoTelaInicioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoTelaInicioMousePressed(evt);
            }
        });

        textoMenuTelaInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoMenuTelaInicio.setForeground(new java.awt.Color(204, 204, 255));
        textoMenuTelaInicio.setText("Tela Inicial");
        textoMenuTelaInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout botaoTelaInicioLayout = new javax.swing.GroupLayout(botaoTelaInicio);
        botaoTelaInicio.setLayout(botaoTelaInicioLayout);
        botaoTelaInicioLayout.setHorizontalGroup(
            botaoTelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoTelaInicioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textoMenuTelaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        botaoTelaInicioLayout.setVerticalGroup(
            botaoTelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoTelaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoMenuTelaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        destaqueLogo.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout destaqueLogoLayout = new javax.swing.GroupLayout(destaqueLogo);
        destaqueLogo.setLayout(destaqueLogoLayout);
        destaqueLogoLayout.setHorizontalGroup(
            destaqueLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        destaqueLogoLayout.setVerticalGroup(
            destaqueLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        botaoMenuGerenciarProduto.setBackground(new java.awt.Color(23, 35, 51));
        botaoMenuGerenciarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMenuGerenciarProdutoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoMenuGerenciarProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoMenuGerenciarProdutoMouseExited(evt);
            }
        });

        textoMenuGerenciarProduto1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoMenuGerenciarProduto1.setForeground(new java.awt.Color(204, 204, 255));
        textoMenuGerenciarProduto1.setText("Gerenciar Produto");
        textoMenuGerenciarProduto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout botaoMenuGerenciarProdutoLayout = new javax.swing.GroupLayout(botaoMenuGerenciarProduto);
        botaoMenuGerenciarProduto.setLayout(botaoMenuGerenciarProdutoLayout);
        botaoMenuGerenciarProdutoLayout.setHorizontalGroup(
            botaoMenuGerenciarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoMenuGerenciarProdutoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textoMenuGerenciarProduto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        botaoMenuGerenciarProdutoLayout.setVerticalGroup(
            botaoMenuGerenciarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoMenuGerenciarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoMenuGerenciarProduto1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        botaoTelaGerenciarEstoque.setBackground(new java.awt.Color(41, 57, 80));
        botaoTelaGerenciarEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoTelaGerenciarEstoqueMousePressed(evt);
            }
        });

        textoMenuTelaGerenciarEstoque.setBackground(new java.awt.Color(41, 57, 80));
        textoMenuTelaGerenciarEstoque.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoMenuTelaGerenciarEstoque.setForeground(new java.awt.Color(204, 204, 255));
        textoMenuTelaGerenciarEstoque.setText("Gerenciar Estoque");
        textoMenuTelaGerenciarEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(4, 60));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout botaoTelaGerenciarEstoqueLayout = new javax.swing.GroupLayout(botaoTelaGerenciarEstoque);
        botaoTelaGerenciarEstoque.setLayout(botaoTelaGerenciarEstoqueLayout);
        botaoTelaGerenciarEstoqueLayout.setHorizontalGroup(
            botaoTelaGerenciarEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoTelaGerenciarEstoqueLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(textoMenuTelaGerenciarEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );
        botaoTelaGerenciarEstoqueLayout.setVerticalGroup(
            botaoTelaGerenciarEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(textoMenuTelaGerenciarEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        botaoTelaGerenciarVenda.setBackground(new java.awt.Color(23, 35, 51));
        botaoTelaGerenciarVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoTelaGerenciarVendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoTelaGerenciarVendaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoTelaGerenciarVendaMousePressed(evt);
            }
        });

        textoMenuTelaGerenciarVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoMenuTelaGerenciarVenda.setForeground(new java.awt.Color(204, 204, 255));
        textoMenuTelaGerenciarVenda.setText("Gerenciar Venda");
        textoMenuTelaGerenciarVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout botaoTelaGerenciarVendaLayout = new javax.swing.GroupLayout(botaoTelaGerenciarVenda);
        botaoTelaGerenciarVenda.setLayout(botaoTelaGerenciarVendaLayout);
        botaoTelaGerenciarVendaLayout.setHorizontalGroup(
            botaoTelaGerenciarVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoTelaGerenciarVendaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textoMenuTelaGerenciarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        botaoTelaGerenciarVendaLayout.setVerticalGroup(
            botaoTelaGerenciarVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoTelaGerenciarVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoMenuTelaGerenciarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/GambiBox/view/imagens/logo.png"))); // NOI18N

        javax.swing.GroupLayout painelMenuLayout = new javax.swing.GroupLayout(painelMenu);
        painelMenu.setLayout(painelMenuLayout);
        painelMenuLayout.setHorizontalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoTelaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destaqueLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(botaoMenuGerenciarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoTelaGerenciarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(botaoTelaGerenciarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelMenuLayout.setVerticalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(nomeLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destaqueLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoTelaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoMenuGerenciarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoTelaGerenciarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoTelaGerenciarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(45, 45, 45))
        );

        tituloTela.setBackground(new java.awt.Color(71, 120, 197));

        textoTituloPagina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoTituloPagina.setForeground(new java.awt.Color(204, 204, 255));
        textoTituloPagina.setText("Gerenciar estoque");

        javax.swing.GroupLayout tituloTelaLayout = new javax.swing.GroupLayout(tituloTela);
        tituloTela.setLayout(tituloTelaLayout);
        tituloTelaLayout.setHorizontalGroup(
            tituloTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoTituloPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tituloTelaLayout.setVerticalGroup(
            tituloTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoTituloPagina, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelAdicionarProduto.setBackground(new java.awt.Color(255, 255, 255));
        painelAdicionarProduto.setMinimumSize(new java.awt.Dimension(800, 600));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(102, 102, 102));
        labelTitulo.setText("Adicionar produto");

        labelNomeProduto.setText("Nome");

        textoNomeProduto.setToolTipText("");
        textoNomeProduto.setEnabled(false);

        labelPreco.setText("Preço");

        labelUnidade.setText("Unidade:");

        selectBoxUnidadeProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "grama (g)", "metro (m)", "centimetro (cm)", "Litro (L)", "ml", "volume", "duzia", "unidade", " " }));
        selectBoxUnidadeProduto.setEnabled(false);
        selectBoxUnidadeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBoxUnidadeProdutoActionPerformed(evt);
            }
        });

        labeldescricaoProduto.setText("Descrição");

        textoDescricaoProduto.setEnabled(false);

        labelCodigoProduto.setText("Código Produto");

        textoCodigoProduto.setEnabled(false);
        textoCodigoProduto.setFocusable(false);

        labelNomeMarca.setText("Nome da marca");

        textoMarca.setEnabled(false);

        labelQuantidade.setText("Quantidade em estoque");

        textFormatPrecoProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        textFormatPrecoProduto.setEnabled(false);
        textFormatPrecoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFormatPrecoProdutoActionPerformed(evt);
            }
        });

        textUnidade2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        textUnidade2.setEnabled(false);

        textoQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        textoQuantidade.setEnabled(false);
        textoQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoQuantidadeActionPerformed(evt);
            }
        });

        jLabel2.setText("Atualizar estoque(Quantidade)");

        atualizaQtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        atualizaQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaQtdActionPerformed(evt);
            }
        });

        jButtonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/GambiBox/view/imagens/adicionar.png"))); // NOI18N
        jButtonAdicionar.setText("Adicionar produtos");
        jButtonAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jButtonRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/GambiBox/view/imagens/remover.png"))); // NOI18N
        jButtonRemover.setText("Remover produtos");
        jButtonRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        checkBoxHabilitarProduto.setSelected(true);
        checkBoxHabilitarProduto.setText("Habilitado");
        checkBoxHabilitarProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkBoxHabilitarProduto.setEnabled(false);

        javax.swing.GroupLayout painelAdicionarProdutoLayout = new javax.swing.GroupLayout(painelAdicionarProduto);
        painelAdicionarProduto.setLayout(painelAdicionarProdutoLayout);
        painelAdicionarProdutoLayout.setHorizontalGroup(
            painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                        .addComponent(labelNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labeldescricaoProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoDescricaoProduto))
                    .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                        .addGroup(painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo)
                            .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                                .addComponent(labelCodigoProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAdicionar)
                                    .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                                        .addComponent(textoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelUnidade))))
                            .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(atualizaQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                                .addComponent(textUnidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectBoxUnidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonRemover))
                        .addGap(18, 18, 18)
                        .addComponent(labelPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFormatPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelNomeMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoMarca)
                            .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                                .addComponent(checkBoxHabilitarProduto)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(34, 34, 34))
        );
        painelAdicionarProdutoLayout.setVerticalGroup(
            painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAdicionarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeProduto)
                    .addComponent(textoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeldescricaoProduto)
                    .addComponent(textoDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCodigoProduto)
                    .addComponent(labelPreco)
                    .addComponent(labelQuantidade)
                    .addComponent(labelUnidade)
                    .addComponent(selectBoxUnidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFormatPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textUnidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNomeMarca)
                    .addComponent(textoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(atualizaQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionar)
                    .addComponent(jButtonRemover)
                    .addComponent(checkBoxHabilitarProduto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelAtualizarProduto.setBackground(new java.awt.Color(255, 255, 255));

        botaoBuscaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/GambiBox/view/imagens/buscar.png"))); // NOI18N
        botaoBuscaProduto.setText("Buscar Produto");
        botaoBuscaProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoBuscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscaProdutoActionPerformed(evt);
            }
        });

        scrollViewTabelaEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrollViewTabelaEstoqueMouseClicked(evt);
            }
        });

        tabelaEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Descricão", "Qtd Estoque", "Unidade", "Tipo Unidade", "Preço", "Marca"
            }
        ));
        tabelaEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEstoqueMouseClicked(evt);
            }
        });
        scrollViewTabelaEstoque.setViewportView(tabelaEstoque);
        if (tabelaEstoque.getColumnModel().getColumnCount() > 0) {
            tabelaEstoque.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        selectBoxFiltroBuscaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome do Produto", "Código do Produto", "Descrição do Produto" }));
        selectBoxFiltroBuscaProduto.setToolTipText("");
        selectBoxFiltroBuscaProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectBoxFiltroBuscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBoxFiltroBuscaProdutoActionPerformed(evt);
            }
        });

        labelBusca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelBusca.setText("Buscar");

        javax.swing.GroupLayout painelAtualizarProdutoLayout = new javax.swing.GroupLayout(painelAtualizarProduto);
        painelAtualizarProduto.setLayout(painelAtualizarProdutoLayout);
        painelAtualizarProdutoLayout.setHorizontalGroup(
            painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAtualizarProdutoLayout.createSequentialGroup()
                        .addComponent(labelBusca)
                        .addGap(18, 18, 18)
                        .addComponent(campoBuscaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(selectBoxFiltroBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollViewTabelaEstoque, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        painelAtualizarProdutoLayout.setVerticalGroup(
            painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBuscaProduto)
                    .addComponent(selectBoxFiltroBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scrollViewTabelaEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelAdicionarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelAtualizarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelAdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelAtualizarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoTelaInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaInicioMouseEntered
        setColor(botaoTelaInicio);
    }//GEN-LAST:event_botaoTelaInicioMouseEntered

    private void botaoTelaInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaInicioMouseExited
        resetColor(botaoTelaInicio);
    }//GEN-LAST:event_botaoTelaInicioMouseExited

    private void botaoTelaInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaInicioMousePressed
        //new TelaInicial().setVisible(true);
        controlProd.newTelaInicial();
        dispose();
    }//GEN-LAST:event_botaoTelaInicioMousePressed

    private void botaoTelaGerenciarEstoqueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaGerenciarEstoqueMousePressed
        // navegação
    }//GEN-LAST:event_botaoTelaGerenciarEstoqueMousePressed

    private void botaoTelaGerenciarVendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaGerenciarVendaMouseEntered
        setColor(botaoTelaGerenciarVenda);
    }//GEN-LAST:event_botaoTelaGerenciarVendaMouseEntered

    private void botaoTelaGerenciarVendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaGerenciarVendaMouseExited
        resetColor(botaoTelaGerenciarVenda);
    }//GEN-LAST:event_botaoTelaGerenciarVendaMouseExited

    private void botaoTelaGerenciarVendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTelaGerenciarVendaMousePressed
        // navegação

    }//GEN-LAST:event_botaoTelaGerenciarVendaMousePressed

    private void selectBoxUnidadeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBoxUnidadeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectBoxUnidadeProdutoActionPerformed

    private void textFormatPrecoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFormatPrecoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFormatPrecoProdutoActionPerformed

    private void textoQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoQuantidadeActionPerformed
        //textoQuantidade = new javax.swing.JFormattedTextField();
        //textoQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
    }//GEN-LAST:event_textoQuantidadeActionPerformed

    private void botaoBuscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscaProdutoActionPerformed

        switch (selectBoxFiltroBuscaProduto.getSelectedIndex()) {
            case 0:
                controlProd.buscaProduto(tableModelEstoque, null, campoBuscaProduto.getText(), null);
                break;
            case 1:
                controlProd.buscaProduto(tableModelEstoque, Integer.parseInt(campoBuscaProduto.getText()), null, null);
                break;
            case 2:
                controlProd.buscaProduto(tableModelEstoque, null, null, campoBuscaProduto.getText());
                break;
            default:
                break;
        }

        limpaCampos();
    }//GEN-LAST:event_botaoBuscaProdutoActionPerformed

    private void selectBoxFiltroBuscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBoxFiltroBuscaProdutoActionPerformed

    }//GEN-LAST:event_selectBoxFiltroBuscaProdutoActionPerformed

    private void botaoMenuGerenciarProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMenuGerenciarProdutoMouseEntered
        setColor(botaoMenuGerenciarProduto);
    }//GEN-LAST:event_botaoMenuGerenciarProdutoMouseEntered

    private void botaoMenuGerenciarProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMenuGerenciarProdutoMouseExited
        resetColor(botaoMenuGerenciarProduto);
    }//GEN-LAST:event_botaoMenuGerenciarProdutoMouseExited

    private void atualizaQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizaQtdActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        // TODO add your handling code here:
        
        int qtd = 0;
        if (atualizaQtd.getText().isEmpty() || tabelaEstoque.getRowSelectionAllowed() == false) {
            JOptionPane.showMessageDialog(null, "Quantidade a ser adicionada, não informada!", "Estoque", JOptionPane.INFORMATION_MESSAGE);
            atualizaQtd.requestFocus();
        } else {

            // pega o valor da quantidade de produtos a ser add 
            qtd = Integer.parseInt(atualizaQtd.getText());

            ImageIcon icon = new ImageIcon("src/com/GambiBox/view/imagens/iconAlerta.png");
            int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente adicionar este(s) " + qtd + "\nproduto(s) ao estoque?", "Adicionando produtos...", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);

            // opção yes
            if (opcao == 0) {

                boolean atualizaEstoq = controlProd.atualizarEstoque(
                        qtd,
                        Integer.parseInt(textoCodigoProduto.getText()),
                        textoNomeProduto.getText(),
                        textoDescricaoProduto.getText(),
                        Integer.parseInt(textoQuantidade.getText()),
                        Integer.parseInt(textUnidade2.getText()),
                        selectBoxUnidadeProduto.getSelectedItem().toString(),
                        Double.parseDouble(textFormatPrecoProduto.getText()),
                        textoMarca.getText(),
                        checkBoxHabilitarProduto.isSelected());

                if (!atualizaEstoq) {
                    JOptionPane.showMessageDialog(null, "Erro ao adicionar produto(s)!", "Estoque", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Produto(s) adicionado(s) com sucesso!", "Estoque", JOptionPane.INFORMATION_MESSAGE);
                    qtd = 0;
                }
            } else if (opcao == 1) {
                JOptionPane.showMessageDialog(null, "Adição cancelada pelo usuário!", "Estoque", JOptionPane.INFORMATION_MESSAGE);
            }

            limpaCampos();
            // Mostra dados atualizados na tabela
            controlProd.buscaProduto(tableModelEstoque, null, "", null);
        }

    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        // TODO add your handling code here:
        int qtd = 0;
        if (atualizaQtd.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Quantidade a ser removida, não informada!", "Estoque", JOptionPane.INFORMATION_MESSAGE);
            atualizaQtd.requestFocus();
        } else {

            // pega o valor da quantidade de produtos a ser add 
            qtd = - 1 * Integer.parseInt(atualizaQtd.getText());
            int tmp = (-1 * qtd);

            ImageIcon icon = new ImageIcon("src/com/GambiBox/view/imagens/iconAlerta.png");
            int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente remover este(s) " + tmp + "\nproduto(s) do estoque?", "Removendo produtos...", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);

            // opção yes
            if (opcao == 0) {

                boolean atualizaEstoq = controlProd.atualizarEstoque(
                        qtd,
                        Integer.parseInt(textoCodigoProduto.getText()),
                        textoNomeProduto.getText(),
                        textoDescricaoProduto.getText(),
                        Integer.parseInt(textoQuantidade.getText()),
                        Integer.parseInt(textUnidade2.getText()),
                        selectBoxUnidadeProduto.getSelectedItem().toString(),
                        Double.parseDouble(textFormatPrecoProduto.getText()),
                        textoMarca.getText(),
                        checkBoxHabilitarProduto.isSelected());

                if (!atualizaEstoq) {
                    JOptionPane.showMessageDialog(null, "Erro ao remover produto(s)!", "Estoque", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Produto(s) removido(s) com sucesso!", "Estoque", JOptionPane.INFORMATION_MESSAGE);
                    qtd = 0;
                }
            } else if (opcao == 1) {
                JOptionPane.showMessageDialog(null, "Remoção cancelada pelo usuário!", "Estoque", JOptionPane.INFORMATION_MESSAGE);
            }

            limpaCampos();
            // Mostra dados atualizados na tabela
            controlProd.buscaProduto(tableModelEstoque, null, "", null);
        }
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void scrollViewTabelaEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollViewTabelaEstoqueMouseClicked


    }//GEN-LAST:event_scrollViewTabelaEstoqueMouseClicked

    private void tabelaEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEstoqueMouseClicked
        // coloca os dados selecionados na tabela nos campos
        selecionaLinha();
    }//GEN-LAST:event_tabelaEstoqueMouseClicked

    private void botaoMenuGerenciarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMenuGerenciarProdutoMouseClicked
        // TODO add your handling code here:
        controlProd.newProduto();
    }//GEN-LAST:event_botaoMenuGerenciarProdutoMouseClicked

    private void setColor(JPanel panel) {
        panel.setBackground(new Color(41, 57, 80));
    }

    private void resetColor(JPanel panel) {
        panel.setBackground(new Color(23, 35, 51));
    }

    public boolean placeHolderCampos() {

        try {
            TextPrompt pldBusca = new TextPrompt("Busca por produtos", campoBuscaProduto);
            TextPrompt pldQtd = new TextPrompt("0.0000", atualizaQtd);

        } catch (Exception e) {
            return false;
        }

        return true;
    }

    public int selecionaLinha() {
        
        int indiceAtual =0;
        try {
            // Pega dados nas linhas da tabela
            indiceAtual = tabelaEstoque.getSelectedRow();

            textoCodigoProduto.setText(tabelaEstoque.getValueAt(indiceAtual, 0).toString());
            textoNomeProduto.setText(tabelaEstoque.getValueAt(indiceAtual, 1).toString());
            textoDescricaoProduto.setText(tabelaEstoque.getValueAt(indiceAtual, 2).toString());
            textoQuantidade.setText(tabelaEstoque.getValueAt(indiceAtual, 3).toString());
            textUnidade2.setText(tabelaEstoque.getValueAt(indiceAtual, 4).toString());
            selectBoxUnidadeProduto.addItem(tabelaEstoque.getValueAt(indiceAtual, 5).toString());
            textFormatPrecoProduto.setText(tabelaEstoque.getValueAt(indiceAtual, 6).toString());
            textoMarca.setText(tabelaEstoque.getValueAt(indiceAtual, 7).toString());

            atualizaQtd.requestFocus();
            atualizaQtd.setText("");
        } catch (Exception e) {
            return indiceAtual;
        }
        return indiceAtual;
    }

    public boolean limpaCampos() {

        try {
            textoCodigoProduto.setText("");
            textoNomeProduto.setText("");
            textoDescricaoProduto.setText("");
            textoQuantidade.setText("");
            textUnidade2.setText("");
            textFormatPrecoProduto.setText("");
            textoMarca.setText("");
            campoBuscaProduto.setText("");
            atualizaQtd.setText("");

            // caixa de nome ganha o focu
            atualizaQtd.requestFocus();

        } catch (Exception e) {
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciarEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField atualizaQtd;
    private javax.swing.JButton botaoBuscaProduto;
    private javax.swing.JPanel botaoMenuGerenciarProduto;
    private javax.swing.JPanel botaoTelaGerenciarEstoque;
    private javax.swing.JPanel botaoTelaGerenciarVenda;
    private javax.swing.JPanel botaoTelaInicio;
    private javax.swing.JTextField campoBuscaProduto;
    private javax.swing.JCheckBox checkBoxHabilitarProduto;
    private javax.swing.JPanel destaqueLogo;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelBusca;
    private javax.swing.JLabel labelCodigoProduto;
    private javax.swing.JLabel labelNomeMarca;
    private javax.swing.JLabel labelNomeProduto;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUnidade;
    private javax.swing.JLabel labeldescricaoProduto;
    private javax.swing.JLabel nomeLogo;
    private javax.swing.JPanel painelAdicionarProduto;
    private javax.swing.JPanel painelAtualizarProduto;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JScrollPane scrollViewTabelaEstoque;
    private javax.swing.JComboBox<String> selectBoxFiltroBuscaProduto;
    private javax.swing.JComboBox<String> selectBoxUnidadeProduto;
    private javax.swing.JTable tabelaEstoque;
    private javax.swing.JFormattedTextField textFormatPrecoProduto;
    private javax.swing.JFormattedTextField textUnidade2;
    private javax.swing.JTextField textoCodigoProduto;
    private javax.swing.JTextField textoDescricaoProduto;
    private javax.swing.JTextField textoMarca;
    private javax.swing.JLabel textoMenuGerenciarProduto1;
    private javax.swing.JLabel textoMenuTelaGerenciarEstoque;
    private javax.swing.JLabel textoMenuTelaGerenciarVenda;
    private javax.swing.JLabel textoMenuTelaInicio;
    private javax.swing.JTextField textoNomeProduto;
    private javax.swing.JFormattedTextField textoQuantidade;
    private javax.swing.JLabel textoTituloPagina;
    private javax.swing.JPanel tituloTela;
    // End of variables declaration//GEN-END:variables
}
